name: Test Workflow

on: push

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: test
    steps:
      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
          dir
      - name: print present working directroy
        run: |
          pwd
          echo "print working directory {{ github.workspace}}"
         