name: Test Workflow

on:
  workflow_dispatch

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: test
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
  
      - name: print present working directroy
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          ls
      - name: execute shell script
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          sh abc.sh
          ls
        working-directory: test
      - name: print list of files
        run: |
          ls
          mkdir demo 
          