name: Test Workflow

on: push

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
          ls
      - name: print present working directroy
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
         