name: Test Workflow

on:
  workflow_dispatch

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: test
    steps:
      # - name: checkout repository
      #   uses: actions/checkout@v4

      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
          
      - name: print present working directroy
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          ls
      - name: execute shell script
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          echo "Runner name is $RUNNER_NAME"
          sh abc.sh
          ls
        working-directory: test
      - name: print list of files
        run: |
          ls
          #mkdir demo

        
        run: New-Item -ItemType Directory -Path "demo/one/two/three/four"
      - name: copy files to relative Path
        shell: powershell
        run: |

           $sourceFolder = "$env:GITHUB_WORKSPACE\demo\one\two\*\four"

           $destinationRoot = "$env:GITHUB_WORKSPACE\output"

           Get-ChildItem -Path $sourceFolder -Filter *.txt -File | ForEach-Object {

           $relativePath = Join-Path "three/four" $_.Name

           $destinationFile = Join-Path $destinationRoot $relativePath

           New-Item -ItemType Directory -Force -Path (Split-Path $destinationFile) | Out-Null

           Copy-Item $_.FullName $destinationFile -Force

      #      }
      # - name: print ls 
      #   #shell: bash
      #   run: |
      #     ls 
      #     echo this is testing
      # - name: copy recursively
      #   run: |
      #     cd "$env:GITHUB_WORKSPACE/demo/one/two"
          

      #     DEST="$env:GITHUB_WORKSPACE/output"

      #     mkdir -p "$DEST"

      #     find three/four -type f -name "*.txt" -exec cp --parents {} "$DEST" \;