name: Test Workflow

on: push

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
  
      - name: print present working directroy
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          ls
      - name: execute shell script
        run: |
          working-directory: test
          echo "print working directory $GITHUB_WORKSPACE"
          # sh abc.sh
          # ls
          