name: Test Workflow

on:
  workflow_dispatch

env:
  NAME: MyWorkflow

jobs:
  build:
    runs-on: test
    steps:
      # - name: checkout repository
      #   uses: actions/checkout@v4

      - name: Print Name
        run: |
          echo "Workflow name is ${{ env.NAME }}"
          
      - name: print present working directroy
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          ls
      - name: execute shell script
        run: |
          echo "print working directory $GITHUB_WORKSPACE"
          echo "Runner name is $RUNNER_NAME"
          sh abc.sh
          ls
        working-directory: test
      - name: print list of files
        run: |
          ls
          #mkdir demo
      # - name: Create a folder using PowerShell
      #   shell: powershell
        
      #   run: New-Item -ItemType Directory -Path "demo/one/two/three/four"
      - name: copy files to relative Path
        shell: powershell
        run: |

           $sourceFile = "$env:GITHUB_WORKSPACE\demo\one\**\three\four\*.txt"
           $relativePath = "three\four\*.txt"

           $destinationRoot = "$env:GITHUB_WORKSPACE\output"

           $destinationFile = Join-Path $destinationRoot $relativePath

           New-Item -ItemType Directory -Force -Path (Split-Path $destinationFile)

           Copy-Item -Path $sourceFile -Destination $destinationFile -Force
          