name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    env:   # ✅ job-level env
      APP_ENV: production
      REGION: us-east-1
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yml
        with:
          app_env: ${{ env.APP_ENV }}
          region: ${{ env.REGION }}